language: python

python:
    - "2.7"

env:
    - DJANGO_SETTINGS_MODULE=__.settings.staging

install:
    - pip install -q -r __/requirements/project.txt
    - pip install -q django-nose

script:
    - python manage.py test
